export const wisdomsEnRaw = [
    "Well, it will die, but just be healthy.",
    "A lamb in a sack is not bought.",
    "Adet is not a law, but a law becomes.",
    "I yours, you ours, who will boil porridge?",
    "I leave him, tobacco, but he doesn't leave me.",
    "I blink and sell, you open your eyes.",
    "I may be small, but sitting on my wallet and getting taller than everyone.",
    "I'm showing you the barn, and you're looking for his door.",
    "Iran has nothing to drink, but goes on a horse to pee.",
    "If Grandma had a mustache, she wouldn't spin sixes.",
    "If it hurts, as it bores him, he should have died a long time ago.",
    "If you kick him out the door, he comes in the window.",
    "If you chase two rabbits, you won't catch one.",
    "If God won't let me, the devil gives a bribe for me.",
    "If God listened to the donkeys, there would be no saddles.",
    "If you go after a beetle, you'll get to shit.",
    "If the day is short, the year is long.",
    "If it's a gargoyle, it's shaggy!",
    "If your wife is very pretty, don't let her go to a wedding alone.",
    "If we live in a village, we don't graze grass.",
    "If there is a mistake, there is forgiveness.",
    "If you want to take, learn to give.",
    "If you want to know a man, give him power.",
    "If you want your head to be at peace, don't put it in the bag.",
    "If youth knew, if old age could!",
    "If you don't patch the old one, you won't wear a new one.",
    "If you don't sow something, you won't reap anything.",
    "If you don't break the mud, you don't make bricks.",
    "If it's not early, you're early.",
    "If you don't want peace, you have an ax!",
    "If there is no mind, are there no legs?",
    "If the priest gets drunk, the village does not sober up.",
    "If work was a good thing and Grandpa Bishop would work.",
    "If the job was over, your grandfather would have done it.",
    "If a hand gives and a heart does not give, nothing happens.",
    "If you pretend to be a lamb, the wolf will eat you.",
    "If you're rich, you're a matchmaker.",
    "If you're a girl, stay home.",
    "If you're a sheep, wolves will always be found.",
    "If he lends you an egg, and it is without yolk. (Squeezed)",
    "If you're going to break your fast, you'd better do it with pork, not cottage cheese.",
    "If you're going to drown, don't bother in shallow water.",
    "Mind - sea, head - buoy.",
    "Mind to the knee, mind to the ankles.",
    "Appetite comes with eating.",
    "Grandma's tales.",
    "Balka vineyard digs, hero drinks wine.",
    "Father's lesson - son's connection.",
    "You can't eat honey without a snag.",
    "Without wet pants, crabs are not caught.",
    "Without science there is no success.",
    "Without work, the holiday is not sweet.",
    "White Kahari.",
    "White money for rainy days.",
    "Pearl is a small berry, but it is highly respected.",
    "Clear water, peaceful head.",
    "Beat the saddle, remember the donkey.",
    "A kind word opens an iron door.",
    "Blessed wine, damn drunkenness.",
    "God high, king far.",
    "God helps, but does not put in the fold.",
    "God suffers, but does not sleep.",
    "He who is healthy is rich.",
    "You stab a stick, you drink wine.",
    "Sick healthy wears.",
    "The potter wants rain, and the tiler wants sun.",
    "Brother brother does not feed, but woe to him who does not have it.",
    "Storm in a glass of water.",
    "Fast as a calf in front of his mother.",
    "Rapid job shame for the master.",
    "Run like the devil from incense.",
    "He was in the tavern, he didn't smell wine.",
    "In him is bread, in him is a knife.",
    "In need, a comrade is known.",
    "If they poke into your eye, you won't see again.",
    "In an open hand a large steam is not released. - the beggar is given very little",
    "In the kingdom of the blind, the one-eyed is king.",
    "Don't put salt in someone else's pot.",
    "Get some water out of the new well, but don't spit in the old one.",
    "Don't leave the evening work for the morning.",
    "Borrowed flour, crushed returns.",
    "She saw the frog shoeing an ox, and she raised her leg.",
    "Wine comes in, words come out.",
    "Wine and grandma rejuvenate.",
    "Wine and Grandpa are playing.",
    "The wine sits quietly only in the barrel; if it comes out of there - it does great damage.",
    "The Vlachs at the end of the Danube are drowning.",
    "Instead of eyebrows to write, eyes out.",
    "Water treads, thirsty walk.",
    "Water washes away everything but shame.",
    "Time is money.",
    "Everyone praises his own, not someone else's.",
    "Everything good has an end.",
    "Each toad to know her bog.",
    "Each swallow praises its nest the most.",
    "Every job praises the master.",
    "Every gypsy woman praises her brooms.",
    "Every tree has a worm to eat it.",
    "A blessing in disguise.",
    "Every miracle in three days.",
    "Yesterday not a penny, today a whole basket.",
    "A wolf in sheep's clothing.",
    "The wolf changes his fur, but his temper - never.",
    "He walks like a beaten dog with a stick.",
    "Tie the priest, may the village be peaceful.",
    "It spins like a headless fly.",
    "The wind blows it on a white horse.",
    "Time is the biggest critic, it will show who is right who is wrong.",
    "Raven raven's eye does not hurt.",
    "There is a head, but there is no head.",
    "The head is not just for a hat.",
    "Hunger sees nothing but bread.",
    "A hungry hen dreams of millet.",
    "Hungry bear horo no the bear does not dance, but when it eats and goes to bed.",
    "Hungry eyes don't sleep.",
    "A hungry dog ​​and a naked bone gnaw.",
    "Vox Populi vox dei.",
    "He looks like a calf on a railroad.",
    "He looks, but he doesn't see.",
    "He gets angry, he sits down.",
    "Great boasting, but small works.",
    "Take a big bite, don't say a big word.",
    "Treat your guest, forgive your enemy.",
    "The blind man exploded and killed a rabbit, and the lame man jumped up and caught him.",
    "Guzen is running away.",
    "Butt head rubs.",
    "There's no bottom.",
    "The gypsy woman swallowed him, so he brags about it himself.",
    "If he sat still, he would not see a miracle.",
    "If you ate, you wouldn't stand.",
    "To be learned - good, to be smart - better.",
    "Let's roll up our sleeves!",
    "If there was cheese, I would grind popara, but there is no bread.",
    "Give me money to buy a purse so I can put my money in it.",
    "May the Lord protect me from my friends, and I will protect myself from my enemies.",
    "Have an earring on your ear!",
    "To catch the bull by the horns.",
    "Gives as much for God to forgive.",
    "Do they give you - hedgehog, do they chase you - run!",
    "He's drowning, but he's not dying.",
    "Two bulls and a cart behind them.",
    "Day of the year food.",
    "The day is known from the morning.",
    "Where the big drum thunders, the small one is not heard.",
    "Where there is a chimney, there is smoke.",
    "No smoke.",
    "We have to buy it today to live it.",
    "Don't leave today's work for tomorrow.",
    "A good word iron door opens.",
    "A good horse makes his own teeth.",
    "A guest came, broke the post.",
    "It brings him to boasting.",
    "While chasing the wild, he lost the tame.",
    "Until you throw in the levels, it doesn't sprout.",
    "While the smart ones think, the crazy ones go crazy.",
    "Bring it, let me put you to eat!",
    "Word does not make a hole, only haber sends!",
    "A tree and a stone to sit, you not to sit.",
    "The tree bends while it is young.",
    "Good is forgotten, evil is never forgotten.",
    "A good horse is known even under a torn sack.",
    "Up to the age of 25 a man marries alone, up to the age of 30 his relatives marry him, and from the age of 30 the whole village marries him.",
    "The mind came, but the godfather went.",
    "As long as she has teeth, the fox pilgrim doesn't get up.",
    "Until you experience evil, you will not know good.",
    "As long as they envy you, rejoice. If they start to feel sorry for you - woe to you.",
    "Until a person dies, the mind gathers and dies again without a mind.",
    "Dirty stick young willow breaks.",
    "A word doesn't make a hole, but a word is chased to a hole.",
    "Cheap flour, expensive bran.",
    "To have a penny, but to give it as a butcher.",
    "One stone gargles three hundred gargoyles.",
    "A bird does not spring.",
    "The tongue has no bones, but it breaks bones.",
    "Cheap meat and dogs don't eat it.",
    "He barely learned to spin and surpassed his master.",
    "One is watching a wedding, another is an ax.",
    "A grave is for both the poor and the boyar.",
    "One is holding the horns, the other is milking the cow.",
    "One stares, another paws.",
    "One drinks and the other pays.",
    "One sows, another reaps.",
    "One was born to sow, another to sing.",
    "One mind - for winter or for summer?",
    "One eats a lemon, another is drooling.",
    "A swallow does not spring.",
    "Some dig and cut, others cut.",
    "One thinks, another says, a third does.",
    "One grandmother knows, one grandmother knows.",
    "Iron is forged while it is hot.",
    "Iron cuts wood and stone, but rust eats it too.",
    "Lives on a wide leg.",
    "Life is not bought with money.",
    "Life is like a ladder - some go up, others go down.",
    "The frog does not croak dry.",
    "Frogs are afraid of storks, women of old age.",
    "A thirsty bear and dew lick.",
    "The thirsty horse and the murky water drink.",
    "If you want someone else's, you lose your own.",
    "A woman knows 'give a man', not 'give a god.'",
    "A woman and a hen have no sign.",
    "A woman and a torn hat are easy to extract.",
    "You can't meet a woman, fire and sea better.",
    "A woman is as sweet as she is bitter.",
    "A woman is the most expensive piece of furniture.",
    "A woman does not beat her husband, but easily defeats him.",
    "The woman doesn't say raft you don't know.",
    "A woman hides her evil like a cat's claws.",
    "If he marries for fun, he will wear horns.",
    "Lazy women - lousy children.",
    "A woman's tongue is sharper than a Turkish sword.",
    "Lives like a flea in a drum.",
    "He lives like a magpie in a fight.",
    "We live as long as the world is not without people.",
    "He lives only to eat, not to work.",
    "They live like a cat and a dog.",
    "They live like a daughter-in-law and a mother-in-law.",
    "There are passengers for every train.",
    "They talk about the wolf, and the wolf in the coop.",
    "To dig a well, dig in one place.",
    "For two bucks he will lay an egg, and for a hundred bucks he will raise.",
    "For the devil incense does not give.",
    "Don't burn the whole rug for one flea!",
    "For praised goods with a cart do not go.",
    "For praised strawberries with large baskets do not go.",
    "Smoothed the hair.",
    "Along with the dirty water, the baby also throws it out.",
    "Rabbits scare.",
    "The law is a door through the field: fools go through the door, thugs split through the field.",
    "The law is for the horse, not for the lion.",
    "Work in vain, do not stand in vain.",
    "Walk in vain, do not sit in vain.",
    "If the craft was learned by watching, the dog would be a butcher.",
    "The craft did not starve.",
    "Stuck like a donkey on a bridge.",
    "The flea burns the quilt.",
    "He ordered him buried under the barrel.",
    "If your wheels get stuck, don't wait for King Marco to straighten them for you.",
    "For the dead either good or nothing.",
    "Why am I a wolf when dogs don't bark at me?",
    "Sturdy as a rock.",
    "Xena, she thought, she said and cut off.",
    "The Lord knows whose oil is burning in the lamp.",
    "Knowledge is power - power is success.",
    "And without roosters dawn.",
    "And the wolf is full, and the lamb is whole.",
    "And undertakers have their undertakers.",
    "And to run, go on the road, seed there.",
    "And if we fall, we will rise again - not to be pots to break.",
    "And the madman runs away from drunkenness.",
    "And he has eyes on his back.",
    "And the warrior himself is a warrior.",
    "And the walls have ears.",
    "Needle in a haystack.",
    "Take out a rusty sword, frighten a cowardly grandmother.",
    "He slipped out of his pants like a fart.",
    "It goes down like a wet string.",
    "Spit out the pebble.",
    "He jumped out like a devil from a bottle.",
    "Property without labor is easily wasted.",
    "If you want a big spoon, get a big hoe!",
    "The truth has come to light.",
    "He who envies does not see",
    "Tell the truth and run.",
    "Tell me what your friends are like so I can tell you who you are.",
    "Tell the blind man that he is blind, and he will be angry with you.",
    "They told the fox, and she told the tail.",
    "A word spoken, a stone thrown.",
    "What mice think, the cat spoils.",
    "What called, called.",
    "What you plant, you will reap.",
    "As the village, so is the mayor.",
    "Whatever you grind, you'll itch.",
    "What is on your pole is on your back.",
    "No matter how you sit, you don't become a musician.",
    "As a hand touched, so a hump wore.",
    "The stone in its place weighs.",
    "They invited the donkey to a wedding, but they ordered him to take a saddle as well.",
    "A drop in the ocean.",
    "A drop of tar barrel of honey spoils.",
    "Drop by drop the pool becomes.",
    "The drop digs the stone not with force, but with perseverance.",
    "When you lift the stick, the guilty cat will run away.",
    "Like two and two - four.",
    "As two drops of water.",
    "Like ass and panties.",
    "If you do not want peace - on your ax. - Khan Krum's supposed words to Nicephorus II",
    "When the upper ceiling hits you, you will bend down to see the lower one as well.",
    "When turning the cart - a lot of roads.",
    "Fun has no price.",
    "Fight fire with fire.",
    "When a man dies, then he becomes good.",
    "When the ates kick, the donkeys pull.",
    "When you walk, look ahead: if you don't find anything, at least you won't stumble.",
    "When something is praised a lot, don't be in a hurry to rejoice early; when something is blackened a lot - don't be in a hurry to deny it in advance.",
    "When you see your ears.",
    "When your mind is weak, your back is strong.",
    "When the facts speak and the gods are silent.",
    "When you praise, you lose nothing; when you curse, you gain nothing.",
    "When the blossoms bloom.",
    "What the devil can't do, he calls the woman to do.",
    "He who lies, he mourns; he who plows, he is well.",
    "He who mixes in honey licks his fingers.",
    "He who mixes in honey often forgets the spoon.",
    "He who has seen the wolf cries, he who has not seen - cries twice.",
    "He who speaks before you behind the back of others will speak before others behind your back.",
    "He who digs the vineyard will eat the grapes.",
    "He who is working will be possessed.",
    "He who envies does not see.",
    "He who has a cow drinks milk.",
    "He who digs the grave of another falls into it himself.",
    "He who buys what he does not need, sells what he needs.",
    "He who reads a lot knows a lot.",
    "He who boasts much, burns slowly.",
    "He who does not work should not eat.",
    "He who is not born will not die.",
    "He who does not bake in the fields does not bake in the dance.",
    "He who draws a knife dies from a knife.",
    "He who has no will, everything is his trouble.",
    "He who does not have, does not like.",
    "He who sings does not think evil.",
    "He who pays badly pays twice.",
    "Whoever pays, orders the music.",
    "He who works honestly will live easier.",
    "He who boasts himself is as if he were boasting himself.",
    "He who struggles, he struggles.",
    "He who laughs last laughs best.",
    "He who toils does not lose.",
    "He who learns will succeed.",
    "He who boasts does not burn; he who is silent does the work.",
    "He who gets dirty, he paws.",
    "He who sits in the mill grinds his flour.",
    "He who walks slowly goes far.",
    "He who sleeps with a dog must also tolerate fleas.",
    "Whoever walks in the yard, he plays the sum.",
    "The hen that lays the most chicks, lays the least.",
    "How much torment the hurricane sees, even on fill the spindle! ",
    "As much as it's nothing.",
    "The more he is silent, the better word he will say.",
    "As much as.",
    "Whoever has the vineyard dug up will have a full barrel.",
    "A cat doesn't fall on its back.",
    "The toads are sniffing through nine lands.",
    "The toad is barking at everyone.",
    "The pear does not fall farther from the tree.",
    "Blood is thicker than water.",
    "Everyone's blood is red.",
    "A grape dog doesn't die.",
    "The dogs are barking, the caravan is moving.",
    "The dog barks to protect not the village but himself.",
    "The dog jumps according to the stick.",
    "Where did you go to eat honey with the bears ?!",
    "Where you do not sow it, there it sprouts.",
    "Where there is no lion's skin, sew the fox.",
    "Where they hate you - don't go, where they love you - don't honor. - don't go often",
    "The dog barks to defend its coma.",
    "There is no finish to Lacardia.",
    "Lying down you can't eat an apple.",
    "It's easy to caress the girls, it's hard to split the beams.",
    "Summer without aba, winter without a bag does not go.",
    "Summer is soft, winter is master.",
    "It's easy to talk, it's hard to do.",
    "It's easy to say, it's hard to prove.",
    "It's easy to spoil, it's hard to do.",
    "It's easy to be a ready-made children's father.",
    "It's easy to promise, it's hard to give.",
    "Summer in the shade, winter in the seats.",
    "A face unseen, soon forgotten.",
    "Libby libe with his flaws.",
    "The fox does not go to the market.",
    "The fox does not fall into the trap twice.",
    "Let the fox and the nun get up, don't let her go between the hens.",
    "The fox loves not the hen, but the hens.",
    "The girl marries the girl.",
    "Vineyard won't Grandpa Pop, he wants Uncle Pot.",
    "The vineyard will not be a prayer, but a hoe.",
    "A bad wound heals, but a bad word is not forgotten.",
    "Bad weather gets better, bad man never does.",
    "A bad word comes out of a bad heart.",
    "We are bad, but we are ours.",
    "The bad guys get along easily.",
    "Bad mouths can say anything.",
    "The evil one sees at night, but he is also afraid of his shadow.",
    "The bad guy is not afraid of the devil either.",
    "The bad man and the pilgrim, he is still bad.",
    "Bad rules, so good never seen.",
    "The bad comes with the car and is taken away with the needle.",
    "Badly with bad expels.",
    "If a bad man grabs your garment, cut it off and leave it in his hand.",
    "There is no crazy fatigue - just sweating.",
    "A crazy girl is known by her big wrist, and a crazy shepherd is known by her big stick.",
    "Crazy did, wise ruined.",
    "Crazy and unsown sprout.",
    "Crazy people don't have a butcher.",
    "Madness is not sold in the market.",
    "Madness is a match for trouble.",
    "A madman plays, a madman plays; he who watches has no mind.",
    "A lie without a padlock.",
    "False water does not tread.",
    "Lying with a spoon does not itch.",
    "The lie goes ahead and the truth goes after it.",
    "The lie goes forward, but it doesn't go far.",
    "The lie does not take root.",
    "Love and cough are not hidden.",
    "An angry man doesn't hold a friend.",
    "Love does not look beautiful.",
    "Summer time without aba, winter time without food does not go!",
    "He goes to bed with the hens, but he gets up with the roosters.",
    "Summer reigns, winter starves.",
    "Donkey doesn't get muddy water.",
    "A donkey doesn't die by a nickname.",
    "A donkey doesn't die of shame.",
    "The donkey doesn't understand out of shame.",
    "A donkey from Timar doesn't understand.",
    "Even if the donkey goes on a pilgrimage, the donkey will return.",
    "The donkey, no matter how small it is, doesn't fit.",
    "I sold my donkey so I didn't get rid of karma donkeys.",
    "Whoever wants the donkey, he buys it without money.",
    "The donkey does not walk on forests and rocks, but on people.",
    "Donkey ride, horse praise.",
    "Donkey riding, donkey looking.",
    "My mother is an expert, she knows how to cook lentils.",
    "The mother of a child does not think evil.",
    "A mother also loves a bald son.",
    "May rains pay off debts.",
    "Yanka is small for digging and big for knocking.",
    "A little cunning, a little grumpy.",
    "Mara leads the dance, a cat eats the flour.",
    "He wagged his tail like a cat for a crumb.",
    "He wagged his dog's tail until he grabbed the liver.",
    "Monkeys with bran are not hunted.",
    "Talk a little and listen a lot.",
    "The little pebble the car turns.",
    "Youth without love - spring without flower.",
    "A lot of words cost a little money.",
    "A lot of talk - on the market.",
    "Wet pants eat fish and dry ones eat peppers.",
    "Wet in a barrel enters, but dry comes out.",
    "Wet from the rain is not afraid.",
    "The girl is not a commodity to keep.",
    "The sea is not knee-deep.",
    "Hoe prayer does not want.",
    "A man under a slipper.",
    "Husband to the best grandmother.",
    "Mushroom like a mushroom - you kick it and fly away.",
    "A male crumb does not weigh on a female.",
    "Shut up like a fish.",
    "Silent as a collision.",
    "Shut up like a grave.",
    "Shut up like a teapot.",
    "Silent as a scythe of eggs.",
    "Shut up like a popcorn.",
    "Shut up like a stump.",
    "Shut up like a fit.",
    "His hands move like a young bride's legs.",
    "The lazy bride against a holiday yarn.",
    "The lazy bride is known for a holiday.",
    "The lazy one the neighbors sleep over.",
    "Lazy evenings are developing.",
    "The lazy man works twice, and the miser pays twice.",
    "Get away, scary, a hero will pass!",
    "The tavern is a trap for drunks.",
    "A bear is not satiated with ants.",
    "Let's lie to you.",
    "Wash as much tar as you want, he's still tar.",
    "My donkey to pay you with punches.",
    "My donkey with soap, you lose both soap and labor.",
    "The past doesn't come back, it just hugs.",
    "Think like an empty manger horse.",
    "It's very bad; it doesn't work until it's beaten.",
    "A lot to talk about, nothing to eat.",
    "Lots of crafts, his hands empty.",
    "A lot of words don't cost money.",
    "Many know how to make money, few know how to keep it.",
    "Many people are born and donkeys die.",
    "Many philosophers graze cattle.",
    "Pray people, may Rada come out maiden.",
    "A maiden gnaws, a head nits.",
    "Maiden gizdosia, bride defeat.",
    "A girl looks like a pumpkin on a fence.",
    "The sea with a spoon is not exhausted.",
    "The girl hated the dance because she married the bastard.",
    "Man - like shit in the rain.",
    "The man is known by the woman.",
    "Lazy women on Saturday nights are developing.",
    "I'm too lazy to watch it.",
    "It's lazy, it hurts.",
    "She's trying to get a girl out of two grandmothers.",
    "He struggles like a sinful devil.",
    "It's hard to fill a torn sack.",
    "It writhes like a slaughtered hen.",
    "It tosses like a fish dry.",
    "That's why the wolf's neck is thick, because he does his own job.",
    "On a bare bedside table a pair of pistols.",
    "On the wire ass green elderberry.",
    "Lie legs are short.",
    "Insolence work when there is no order.",
    "Our garge is always the best, our house is the most tidy.",
    "Don't brag about who you were, but what you are now.",
    "He walks around like a cold donkey.",
    "They love each other like a dog and a cat.",
    "The shoemaker walks barefoot.",
    "The cobbler walks with torn shoes.",
    "Turn the petals.",
    "He looked around like a robbed Jew.",
    "The horse goes to the river.",
    "An eye to see and a hand to touch.",
    "An eye for an eye, a tooth for a tooth - of biblical origin",
    "He anointed himself as a halvadji Tesla.",
    "You burned the job.",
    "He twisted the threads and threw the cannon.",
    "He slapped himself like an ajamia midwife.",
    "He slapped himself like a Halva's Tesla.",
    "Ori and sei while the lazy one sleeps.",
    "Ori, dig, eat, don't get rich by grabbing.",
    "The wolves ate it.",
    "The little mare ate the dog.",
    "He listens like a pickpocket in corn.",
    "A rabbit doesn't come out of every thorn.",
    "Not every tree blows a whistle.",
    "Once in a blue moon.",
    "They eat beans from one pot and still think they're smarter than each other.",
    "There is no worse craft than stubbornness.",
    "From a horse to a donkey.",
    "From a bad debtor and a basket of chaff is good.",
    "From me to pass.",
    "You don't get rich from a lot of work - you get rich.",
    "You can't make a tailcoat.",
    "You don't look good from work, you turn your back.",
    "From hard work, without hard work.",
    "From small coins become coins.",
    "It's from an old goat goat.",
    "From the cold forges.",
    "From pumpkin seeds alabaster (Brussels sprouts) will not sprout.",
    "From thorn to hawthorn.",
    "It suits him - like a pig's bell.",
    "If you go to Rome, do as the Romans do.",
    "Discovered America.",
    "He finally found the wheel.",
    "He finally found hot water.",
    "Where it came from, it went there.",
    "Wherever it passes, there is no grass.",
    "It broke from his heart.",
    "My hands are torn off.",
    "Eyes full, hands empty.",
    "Eyes that cannot be seen are forgotten.",
    "The eyes see everything, but not themselves.",
    "Steamed porridge spirit.",
    "Money goes with money.",
    "Money deceives the woman, and the woman deceives the man.",
    "Pachavra doesn't catch lightly.",
    "The dog barks to keep his coma.",
    "Five Petko are not waiting!",
    "She drank goat wine that was looking for the wolf to fight.",
    "They drank - they sang, they paid - they cried.",
    "Chickens are counted in the fall.",
    "They asked the wolf: why is your neck thick? He said: because I do my own job.",
    "Spit on your hands!",
    "In clothes they welcome, in mind they send.",
    "Better a poor horse than no horse at all.",
    "Better to have a bad brother than a bad neighbor.",
    "Let's get to drink now.",
    "Pull your leg.",
    "Under the ox calf is looking.",
    "Under a big rock - a big fish.",
    "Under the road and over the road.",
    "If you give your puppy - it will bite your hand.",
    "He invited me to visit, to teach me to fast.",
    "Coated milk cats don't secrete.",
    "He tried to swallow a buffalo, he caught a fly.",
    "His job has grown.",
    "The last hole in the kaval.",
    "Smile a little. - to someone who brags a lot, promises or exaggerates",
    "Dip your tongue in your brain, then come to your senses!",
    "Sweat is like a bee: wherever it goes, it always carries.",
    "The donkey began to roar and brag about how he was tossing in the dust in the middle of the square.",
    "You're right wrong.",
    "An empty praise bag does not fill.",
    "Send it for green xiver. ",
    "Put your finger on it and go around the village to see how many doctors you will meet.",
    "Elijah changed, looked at himself - again at these.",
    "Skip, then shout 'hop.'",
    "He laughed at the stump.",
    "Sew a button on the button.",
    "A friend in need is a friend indeed.",
    "Friendship is friendship, but cheese is about money.",
    "They put Tarlio under the bed, he got on the bed.",
    "Let him graze.",
    "Better late than never.",
    "Under old clothes, you'll often recognize a good drunk.",
    "Let the work be afraid of you, not you of it.",
    "His job is working.",
    "His work alone praises him.",
    "The work of the mind teaches.",
    "Work does not threaten man, laziness threatens him.",
    "He works without pay, he doesn't go without work.",
    "Works like a bug, eats like a bear.",
    "It works like a hall.",
    "Works from dark to dark.",
    "Work as if you will live a hundred years, and live as if you will die tomorrow.",
    "It only barks the dogs - that is, it makes noise, trumpets and provokes emotions, resentment, indignation at something insignificant, frivolous",
    "He disintegrated like an Ahiev reader.",
    "Early chicken sings early.",
    "Rove to the black donkey in the hollow.",
    "The fish in the sea, and we put the cauldron on it.",
    "The fish still in the sea, he prepared the pan.",
    "The fish smells from the head.",
    "Kick the bell.",
    "They rusted his money in his purse.",
    "Hand washes to make them both white.",
    "With the wolves howl like a wolf.",
    "With one foot in the grave.",
    "With one hand he gives, with two he takes.",
    "Geranium is not dug with a needle.",
    "What you get together with, you become.",
    "With bloody sweat.",
    "He went with the bears to eat honey, too.",
    "With money in heaven, no money at the end.",
    "With song, work is easy.",
    "You can get to Constantinople by asking.",
    "They catch the wind with a sieve.",
    "To turn with a thorn, there is nothing to hang.",
    "With someone else's pie, a memorial service is held.",
    "Touching hot iron with other people's hands is not difficult.",
    "Sword to war does not lend.",
    "Do the job like the dog on the levels.",
    "The brandy is over, the lacardia is over.",
    "A cohesive company raises the mountain.",
    "The strong man halves the days.",
    "The Simidchi, if he does not praise the Simids himself, will not sell them.",
    "Poor man - living devil.",
    "Poverty is afraid to enter a hard-working woman.",
    "Sit on the hungry does not believe.",
    "The full guest is difficult to entertain.",
    "Sparrows quarreled over other people's millet.",
    "After a good job - good food.",
    "After the rain hood.",
    "Lay his horns.",
    "A humble sword's head does not cut it.",
    "The hen laid an egg and squawked the whole neighborhood.",
    "Own load does not weigh.",
    "Salt is added but not removed.",
    "Shame is not washed away with water.",
    "It became the laughter of the hens.",
    "Old board paint does not catch.",
    "Old love does not rust.",
    "It's got under the pear curve.",
    "It's a shot rabbit.",
    "One hundred watched, one saw and he was blind with one eye.",
    "Dry as cirrhosis.",
    "Dry sex does not eat fish, but wet.",
    "You break, you buy!",
    "The sun does not rise for one.",
    "Do you dream of a pie - eat!",
    "Angry Petko, his bag is empty.",
    "Look for it with a candle.",
    "Do not go to a foreign monastery with your psalter.",
    "I just taught the donkey not to eat and it died.",
    "I lie to you - the truth to me.",
    "Woe to the clever among fools.",
    "You work, I will help you, said God",
    "Quiet water is the deepest.",
    "What is not there and the king does not eat it.",
    "Tray grandma for beauty.",
    "Tray, horse, for green grass.",
    "Measure three times, cut once.",
    "I cut three times and it's still short.",
    "Work is health and life.",
    "The sea went into the river to drown.",
    "Thin as a poplar.",
    "The drum is big, but it's empty.",
    "Mother-in-law turns.",
    "Tafra strains me - Golocha stumbles me.",
    "Everyone has a conscience, but blessed is he to whom it is pure.",
    "Everyone has a little honor.",
    "Everyone has a mind for a couple.",
    "There is no new pot in a potter.",
    "At nine knots it ties one pair.",
    "The son-in-law's drum beats, and the bride has no idea.",
    "Whoever has the pie has the knife.",
    "In the legs they shine, in the head they collide.",
    "The girl has a blunt drum, the boy has no idea.",
    "A murderer is not one who makes knives, but one who kills with them.",
    "It's stuck like a horsefly under a tail.",
    "He fattened up like a Danube pig.",
    "He fattened up like a barren cow.",
    "Hit him on the run.",
    "Hit him alive.",
    "Hit him on request.",
    "Hit him through the millet.",
    "Hit the kelepira.",
    "Hit the skinny one.",
    "Hit him with an ax on a stone.",
    "Hit the eggs on the butter.",
    "She hit his hair on a rock.",
    "It went to his mind.",
    "Caught her by the tail.",
    "Mind to give - a lot, money - no one.",
    "Mind and reason are not bought with money.",
    "The mind makes, the head pulls.",
    "Mind with a car, memory with a fork.",
    "Mind doesn't buy with money, so it costs the most money.",
    "The mind reigns, the mind enslaves, the mind feeds the ducks.",
    "It simply came to our notice then - splits the thread and the flea slacks do. ",
    "Be able to sing, don't be able to sing.",
    "Smart as a hog.",
    "Smart as nine catches.",
    "Wash your feet, that the king may pass away!",
    "The spoon was washed, so it became a bowl.",
    "He dies and oversees in a pot.",
    "I'm starving.",
    "The dying woman fixes everything.",
    "He thought like a dog during Lent.",
    "He thought, as if his gems had sunk.",
    "A smart woman is worth more than a diamond.",
    "Smart men respect women.",
    "The clever one even makes a living in his sleep.",
    "The clever one earns his living everywhere.",
    "The clever man in anger knows himself.",
    "Die, but don't steal.",
    "Die, but don't pass; if you pass, don't betray; if you betray, don't care.",
    "Die, Dad, let me eat wheat.",
    "The ox died, the ortaklak broke down.",
    "He died with his eyes open.",
    "The gypsy who praised him died.",
    "A dead horse doesn't kick.",
    "A dead horse of wolves is not afraid of him.",
    "I died for him.",
    "The cat died and thought about mice again.",
    "The dead donkey from the wolf is not afraid of him.",
    "I died laughing.",
    "My mind doesn't fit it.",
    "His mind is at his feet.",
    "My eye is scared.",
    "Frightened like a wolf in a thousand sheep.",
    "He twisted the threads and kicked the cannon.",
    "Enchanted by the red.",
    "Mara felt that there was a bar under her.",
    "Service for service.",
    "Why are they mouths if they don't praise me?",
    "There is a mouth, there is no tongue.",
    "Dog's mouth, it's eating.",
    "His mouth is like a mill.",
    "His mouth still smells of milk.",
    "Close your mouth, open your eyes.",
    "Comfort the sick until his soul jumps out.",
    "The bride used one corner and settled in the other.",
    "The morning is wiser than the evening.",
    "He was bitten by a bee by the tongue - he shouts a fefel.",
    "He grinned under his mustache.",
    "A scientist to beat you, just not to caress you.",
    "A scholar to the threshold, and a clever to the age.",
    "The teaching has no end.",
    "Teaching is not a king to drink to become a scientist.",
    "Learn from an early age, when you grow old you don't feel sorry.",
    "She's supposed to be smart, but with a duck's mind.",
    "Haber is out of the world.",
    "You have no idea that the earth rotates.",
    "Eat kume beans! - I'm fine with caviar too!",
    "It is spent like hot bread.",
    "The king's daughter got to work, and her hands splashed.",
    "Catch one, hit the other.",
    "The cunning magpie, with both feet.",
    "Human mouths haven't heard you tie them.",
    "Food has saved humanity from starvation.",
    "Feed the dog to bark at you.",
    "Nice work, but gypsy.",
    "Nice apples are eaten by pigs.",
    "A good horse is known even under a torn sack.",
    "He ran headlong.",
    "The king gives, the father does not give.",
    "A glass full, a woman hungry.",
    "Black Gologan is not lost.",
    "One knows both two and two hundred.",
    "One does not live on bread alone.",
    "One learns from what happened to him.",
    "Through audacity to progress.",
    "The foreign hen - a goose.",
    "Foreign bread - teeth break.",
    "The awl doesn't sit in the bag.",
    "Wide around his neck.",
    "Shushu-mushu house is ruining.",
    "It will gather a home as much as drummed dust.",
    "A bear will trample you!",
    "What is in the hand is not a lie.",
    "What did I need from a bear strap?",
    "What he thinks sober, drunk says it.",
    "It will pass like a dog.",
    "If there is a mistake, there is forgiveness.",
    "Once you're hooked on the dance, you'll play it.",
    "A young man without a wound does not walk.",
    "You are a hero on horseback, and the frog raises its leg.",
    "The quilt burned, he pities the threads.",
    "He eats like a bear and works like a stick.",
    "Eating on eating goes, only fight on fight doesn't work.",
    "The egg teaches the hen.",
    "Like a bull.",
    "I'm a camel, I'm a camel.",
    "God gives, but does not put in the fold.",
    "Rapid job shame for the master.",
    "The wolf changes his fur, but his temper does not.",
    "A hungry hen dreams of millet.",
    "Eat a big bite, don't say a big word.",
    "A big wound heals, a bad word is not forgotten.",
    "God is slow, but he does not forget.",
    "Guzen is running away.",
    "If he sat still, he would not see a miracle.",
    "Two sharp stones do not grind flour.",
    "Two quarrel, a third wins.",
    "Thick snow - a big coma.",
    "The day is clear in the morning.",
    "Good word, iron doors open.",
    "Deep water - no ford, beautiful girl - no kind.",
    "The devil is not afraid of incense.",
    "The tongue has no bones, but it breaks bones.",
    "Iron is forged while it is warm.",
    "There is an herb for every pain.",
    "For a penny a rooster, for a penny sings.",
    "You can judge a man by his friends.",
    "And without a cock it gets dark.",
    "Either be young women, or young monks.",
    "The stone weighs in place.",
    "Drop by drop - a whirlpool becomes.",
    "I tell you daughter - remember daughter-in-law.",
    "Whatsoever a man soweth, that shall he also reap.",
    "Fight fire with fire.",
    "He who hurries slowly goes far.",
    "He who does not guard another's will not have his own.",
    "He who has no mind has legs.",
    "Whoever pays, orders the music.",
    "He who laughs last laughs best.",
    "Who plays good on the whistle - he doesn't need a drum.",
    "Which hen screams a lot, lays a few eggs.",
    "He who is afraid of a bear, let him not go into the forest.",
    "He who does not work should not eat.",
    "What sheep is separated from the flock, the wolf eats it.",
    "Let's sit crooked, let's judge right.",
    "The pear does not fall farther from the tree.",
    "Blood is thicker than water.",
    "The dogs are barking, the caravan is moving.",
    "Where you see a village of nine houses with ten pubs, run away from it.",
    "Summer without aba, winter without a bag - do not walk.",
    "The vineyard does not want prayer, but a hoe.",
    "A bad word comes out of a bad heart.",
    "The little stone the big car turns.",
    "Many grandmothers - a weak child.",
    "Silence is golden.",
    "Laziness does not kill, it kills.",
    "Lie legs are short.",
    "Beauty does not happen by force.",
    "On someone else's back and a hundred sticks are few.",
    "Hope maintains a person.",
    "Get the lazy one to work, teach you a lesson.",
    "He who eats the pie is not mad, but he who gives it to him.",
    "You can't carry two watermelons under one arm.",
    "No one is greater than bread.",
    "No one was born a scientist.",
    "New day - new luck.",
    "Know your motherland, to love it.",
    "Not every tree blows a whistle.",
    "There are no memories from the dream.",
    "Eyes that cannot be seen are forgotten.",
    "Steamed porridge spirit.",
    "Chickens are counted in the fall.",
    "In clothes they welcome, in mind they send.",
    "Along the dry forests and the wet.",
    "Help yourself and God help you.",
    "An excessive saint is not dear to God either.",
    "A friend in need is a friend indeed.",
    "Stretch according to your rug.",
    "The fish smells from the head.",
    "She gave birth to me, mom, with luck, so she threw me in the trash.",
    "What you get together with, you become.",
    "You can get to Constantinople by asking.",
    "Bran monkeys are not hunted.",
    "With hard work and perseverance, everything is achieved.",
    "With someone else's pie, a memorial service is held.",
    "A cohesive company raises the mountain.",
    "Poor man, living devil.",
    "The city of the hungry does not believe.",
    "Modesty adorns man.",
    "Expensive flour, cheap brandy.",
    "Shared sorrow - half sorrow, shared joy - double joy.",
    "Nobody is against rakia, the ones who are - are kicked.",
    "An old ox is hard to harness.",
    "Old love does not rust.",
    "Measure three times, cut once.",
    "The mind reigns, the mind enslaves, the mind feeds the ducks.",
    "The morning is wiser than the evening.",
    "Harizan horse's teeth are not watched.",
    "Good things happen slowly.",
    "The king giveth, the king does not giveth away.",
    "Man presupposes, and God disposes.",
    "A bird does not spring.",
    "While the wise are wise, the foolish are driven mad.",
    "The new broom sweeps clean, but the old one knows the corners.",
    "If you don't patch the old one, you won't wear a new one.",
    "In the kingdom of the blind, the one-eyed is king.",
    "He who is healthy is rich.",
    "In need a comrade is known",
    "Clear water, peaceful head",
    "A kind word opens an iron door.",
    "God suffers but does not sleep.",
    "If youth knew, if old age could!",
    "If a hand gives and a heart does not give, nothing happens.",
    "Without wet pants, crabs are not caught.",
    "If there is a mistake, there is forgiveness.",
    "If you want to take, learn to give.",
    "One stares, another paws.",
    "To be learned - good, to be smart - better.",
    "A guest came, broke the post.",
    "The tongue has no bones, but it breaks bones.",
    "Life is not bought with money",
    "Cheap meat and dogs don't eat it.",
    "If you want someone else's, you lose your own.",
    "The law is for the horse, not for the lion.",
    "Property without labor is easily wasted.",
    "They told the fox, and she told the tail.",
    "It's easy to promise, it's hard to give.",
    "Even if the donkey goes on a pilgrimage, the donkey will return again.",
    "A face unseen, soon forgotten.",
    "Many know how to make money, few know how to keep it.",
    "Let the fox and the nun get up, don't let her go between the hens.",
    "A madman plays, a madman plays; he who watches has no mind.",
    "That's why the wolf's neck is thick, because he does his own thing.",
    "It is not the good in the many, but the many in the good.",
    "He who thinks evil finds evil.",
    "He who thinks whatever will overwhelm him.",
    "A friend in need is a friend indeed.",
    "Noble is the virtuous, not the great.",
    "Hands praise the face.",
    "Good wants you to drive it, and evil just goes.",
    "Labor begets good, and laziness begets evil.",
    "Where a fast girl gets married, poured on toad bachelors.",
    "A crooked foot distorts the shoe, and the wrong people distort the work.",
    "Don't ask the old man, but the sufferer.",
    "Good word, iron doors open.",
    "It's a hat to buy you, but I can't mind.",
    "Lying with arshin does not measure.",
    "If you're not right, you're wrong.",
    "Wait from a stranger right, as from a madman.",
    "No old step, torn drum.",
    "Better a thousand friends than a thousand pennies (levs).",
    "Foreign hands do not itch.",
    "While the wise were wise, the foolish were mad.",
    "Where a lot of wine is drunk, another does their job.",
    "Don't ask about the crazy, but listen.",
    "White hands, hwork. ",
    "Don't go down into the well with a rotten rope.",
    "The fish smells from the head.",
    "Whoever steals a needle will steal the treasury.",
    "As long as the lines are not torn, the curves are not detached.",
    "Where the old do not listen, the young do not spoil.",
    "Where the old are not revered, there for good do not ask.",
    "If a fortune teller knew, she would know about herself.",
    "Do not believe the ears, but the eyes.",
    "Where the heart is, there the eye.",
    "Don't praise a personal girl, but a smart one.",
    "Beauty is not seen in a man.",
    "Stretch according to your rug.",
    "If you want someone else's, you lose your own.",
    "Foreign money, fingers burning.",
    "If you go for a bee it will take you to honey, if you go for a beetle it will take you to the garbage.",
    "If you want to take, learn to give.",
    "Whatever dance you take, you will play such a game.",
    "What you want others to do to you, do to them.",
    "A good woman doesn't go without a job.",
    "Where the power reigns, there the law swings.",
    "The master eye costs more than ten foreign hands.",
    "Where there is color, there is honey.",
    "Half heart, half work.",
    "An empty sack, not sitting straight.",
    "Act wisely, don't run crazy.",
    "He who does not measure by measure has no faith (he who has no measure has no faith).",
    "There is no worse craft than stubbornness.",
    "In reality he watches over ants, in the dark he steals horses.",
    "Let another praise you, not himself.",
    "Where there are many roosters, there it is late.",
    "The wolf changes his fur, but not his temper.",
    "In a boat with a lot of captains, the crazy ones ride.",
    "Rust in gold does not catch.",
    "Beat good, better.",
    "From bad, worse.",
    "Where words don't help, there's a stick.",
    "An empty bag is heavier than a full one.",
    "Where it's thin, it breaks.",
    "Raven on raven eyes do not take out.",
    "He is afraid of a Greek lie and the gypsy.",
    "To fight with a shit, to make a mess.",
    "Watching satiety does not give.",
    "Because it is a shame, it is a sin.",
    "Head without rust, on a watermelon pumpkin.",
    "You look at a person's face, you don't know his heart.",
    "Every evil has its death.",
    "Stupid walk, hungry - no.",
    "Guzen (guilty), fleeing impassively.",
    "Guest the guest, forgive the enemy.",
    "Where there is a lot of manure, there is a lot of controversy.",
    "Health is the greatest wealth.",
    "When a person is healthy and his water is sweet.",
    "If there is a mistake, there is forgiveness.",
    "He who does what he does to himself.",
    "He who digs the grave of another falls into it himself.",
    "He who eats two vegetables is not mad, but he who gives them to him.",
    "No health property, hated life.",
    "Power without reason, it destroys itself.",
    "Show me your friends and I'll tell you who you are.",
    "Bad heart, remember bad.",
    "Listen a lot, think a little.",
    "A bad word from a good heart does not come out.",
    "From a knife a wound heals, from an evil word - never.",
    "Money does not buy health, but takes it.",
    "He who leans on steam loses his humanity.",
    "Measure three times, cut once.",
    "Money is a document, not a goal.",
    "Donkey muddy mud does not tread.",
    "Everyone learns from what happened to them.",
    "It doesn't matter who gave birth to you, it matters who raised you.",
    "A thousand look, take one.",
    "Everything is achieved with patience.",
    "A blind man for a road and a fool for advice don't ask.",
    "He who flies high falls low.",
    "Don't trust the nobleman, he's skinning you.",
    "Kukurigo-kudkudyak, bragging is a fool.",
    "The little stone overturns the car.",
    "When, when that never.",
    "Where there is property, there is the soul.",
    "The good one will beg, but he will not steal.",
    "Every new, forgotten old.",
    "Good does not need praise.",
    "He who lies once is not believed forever.",
    "The right one laughs, the crooked one hides.",
    "He who draws a knife dies from a knife.",
    "Poverty does not enter a co-operative house.",
    "A stick breaks easily, but a bundle is difficult.",
    "Vox Populi vox dei.",
    "He who sows reaps.",
    "Little alms saves from great troubles.",
    "The wolf, the bigger the white one does.",
    "In clothes they welcome you, in mind they send you away.",
    "The mind doesn't buy with money, it costs the most money.",
    "Rest, only after work is sweet.",
    "The praiser and the Lord do not tolerate him.",
    "The Lord is with those who love the law, and the staff with those who love the forest.",
    "The wolf's name works, and the fox does its own thing.",
    "It is better to weep with the wise than to lie with the fool.",
    "Better to cry with the smart than to jump with the crazy.",
    "It is better for a child to cry than for a mother to cry.",
    "Covered milk, the cat does not eat it.",
    "The good one looks at himself and the bad one at others.",
    "The bad person remembers the bad.",
    "Slide with your foot, with your tongue, don't.",
    "He who considers himself better, smarter and richer has no real friends or faithful brother.",
    "Better alone than with a bad man.",
    "Leave the madman alone, let his mind come.",
    "Good is sweet when it comes to a little.",
    "Everyone has to give the thief.",
    "Many grandmothers, skinny child.",
    "His beard is early, his mind is delayed. ",
    "Where your hands don't fit, don't push your head.",
    "Laziness is the parent of evil.",
    "Everything is achieved with perseverance.",
    "Coal, more money.",
    "Take a fly, take you to shit.",
    "Slowly touch, far tick.",
    "Lie legs are short.",
    "Expose the wise to find a friend; Expose the wicked to find an enemy.",
    "Better dry bread with peace than many dishes with sorrow.",
    "He who imitates without understanding finds trouble.",
    "Better late, but whole.",
    "Whatever you come together with, you will become.",
    "Whoever does what they can, is what they are looking for.",
    "You take a man by force, but you cannot give him by force.",
    "Tour's mind doesn't sit in his head.",
    "It helps the generous and the devil.",
    "A bowed head, a sharp sword does not cut it.",
    "He who envies does not see good.",
    "To the envious, his world is to blame.",
    "Truth wings and lies suffocate.",
    "We don't live to eat, we eat to live.",
    "Fear the cunning, not the foolish.",
    "Beware of him who speaks one thing and does another.",
    "If you are a bee to carry honey, come in the future and eat it, go where you want.",
    "The little bird's mouth gets big.",
    "You have a little intelligence, but it's in your place.",
    "Money deceives the woman, and the woman deceives the man.",
    "Words draw more accurately than gold.",
    "It doesn't matter who gave birth to you, it matters who raised you.",
    "Do not raise a larger shadow than your paint.",
    "In a clever head a hundred hands.",
    "Let me know that let them rebuke me, not let me not know, let them praise me.",
    "One does not lie, one does not learn.",
    "A scientist to beat you, just not to caress you.",
    "A man forgives himself.",
    "To the poor guest go eat, to the boyar-go try.",
    "The best apple, the pig eats it.",
    "From heard to seen, very far away.",
    "God forbid from the Greek and from the Turks.",
    "A scalded dog runs away from the rain.",
    "Steam, porridge of the spirit.",
    "The horse knows who can ride it.",
    "Where there are more queues, there are fewer heads.",
    "The smaller you are, the smaller you always show up.",
    "Open your mouth only for good.",
    "Luck without a mind does not cost a niche.",
    "A teacher is chosen not by the beard, but by the head.",
    "Sow action, you will reap habit.",
    "A peaceful heart prays to God, and restless tears shed tears.",
    "No crooked, no right.",
    "The wood bends while it is thin.",
    "At an evil hour you can see who is who.",
    "To an unwanted person, his place is outside the door.",
    "While one does not pull, another does not get rich.",
    "As long as the fox has teeth, the pilgrim doesn't get up.",
    "Think of good, lest evil come upon you.",
    "Do not climb a tree without a root.",
    "She hired a rope to crawl on her forehead.",
    "It wouldn't be a cramped house if it weren't for the rage.",
    "Keep your soul, so that your flesh does not get sick.",
    "He learned naked, so he threatens to be dressed.",
    "A priest has learned roasted beans, a bean has ended - a priest has learned.",
    "Foreign food, wolf food.",
    "Feed the wolf in the winter, eat you in the summer.",
    "To be learned-good, to be smart-better.",
    "Good word, no price.",
    "Nice girl, but sleepy.",
    "A friend knows each other on the road.",
    "A man's beauty is not seen.",
    "A boy with his father's money, hungry old men.",
    "A hero in clothes is not known.",
    "A cohesive company, the mountain raises.",
    "Every nation deserves its rulers.",
    "Everyone gets what they deserve.",
    "Don't look at the bark, but the middle.",
    "There is no scale on a lie.",
    "Everyone loves who looks like him.",
    "If there is science, there is science.",
    "If you don't value the small, you won't have the big.",
    "Grandma does, the devil is glorified.",
    "Grandma's praise, full bag.",
    "Don't put salt in someone else's pot.",
    "Liar, only the first year he enjoys his lie.",
    "What is done without a plaintiff is not worth a Friday.",
    "He grew up with a hard mind, he lay down softly, his mind lay down.",
    "Until he gets burned, he doesn't understand.",
    "Because of one donkey, he doesn't hate an entire village.",
    "The more flexible, the harder.",
    "Don't run away from your first luck.",
    "Don't look at my hat, but under my hat.",
    "On someone else's back, a hundred sticks are nothing.",
    "What is in his heart, is in his mouth.",
    "Where they hate you don't go, where they love you don't go often.",
    "If you don't hold it by the head, you can't hold it by the tail.",
    "If it's hard to give, it's harder to ask.",
    "To recognize someone, give them a job in hand.",
    "If you do not see evil, you do not know good.",
    "Where two fight, don't get third.",
    "If justice does not help, then injustice never.",
    "The barking of the dog, the hotness of the pepper, and the kindness of the man are revered.",
    "Don't you understand, don't talk, but ask and learn.",
    "He does good well and thinks of the rock.",
    "Young works, old mind come on.",
    "Young vine, sour grapes.",
    "Silence that the wolf ate you.",
    "On wood with children instead of help plague.",
    "Slowly, close to far.",
    "Everything is easy for the industrious and difficult for the lazy.",
    "The human eye is not satisfied.",
    "In the eyes of the darling, behind the eyes of the enemy.",
    "A man with a mustache and a woman with breasts do not study.",
    "A request is not a loss.",
    "Forced beauty does not happen.",
    "My ass to pay you with a punch.",
    "From a full wolf and from an old Greek, God bless you.",
    "It's better to spend less than to earn more.",
    "Don't ask me where I'm going, but where I've been.",
    "Be afraid of a foolish friend, and not of a wise enemy.",
    "On someone else's back life, dull family.",
    "To a good son, why property? And to a bad one.",
    "Happy is he who is grateful for what he has.",
    "To believe in good, give up evil.",
    "Only one Lord is infallible.",
    "What the wise man is ashamed of, the foolish man is proud of.",
    "A blessing in disguise.",
    "Granny works, granny don't sit.",
    "He who works honestly, with the mind, has everything at home.",
    "An eye to see, a hand to touch.",
    "He who is weak in the head, let his legs be strong.",
    "If you have some flour, give it to the baker to bake for you.",
    "You have to hit the upper threshold to know that there is a lower one.",
    "He is rich who does not need riches.",
    "Playing with another woman, in your house chief.",
    "Empty barrel, louder.",
    "And the wolf is full, and the lamb is whole.",
    "If you want your head to be at peace, don't put it in the bag.",
    "He who lies lies to himself.",
    "If you flee from good, evil will befall you.",
    "When they want three hundred, they don't ask the priest Christ.",
    "When the cat is gone, the mice dance.",
    "When an enemy runs away, make him a golden bridge.",
    "If you sweeten it, it will stick to you.",
    "If you give here, you'll find there.",
    "If it's yours, it'll be yours.",
    "If you go around, you'll go.",
    "If there's a hook, there's a hook.",
    "If you want a job done, do it yourself.",
    "On goofy eyes, glasses don't help.",
    "A man's eyes should come out, so that no word will come out.",
    "He who wants power is the same as he who has it.",
    "What are you going to tell him, mango, tell him ago to be glad.",
    "A wolf with a haber lamb does not eat.",
    "A guest hates another guest, and the host both.",
    "It is not the one who thinks evil that gets sick, but those who think evil.",
    "Don't grow high on your mind.",
    "Work teaches the mind, and laziness teaches lies.",
    "You don't fight with a horn, you don't fight with a rich man.",
    "Where you see a village with nine houses and nine pubs, run away from it.",
    "Labor adorns man, and laziness destroys him.",
    "Half heart, half work.",
    "What the heart is full of, the mouth speaks.",
    "Accumulate only what a moth does not eat and a thief does not steal.",
    "People are not measured by their feet, but by their minds.",
    "What you've crushed, you'll itch.",
    "Quiet water is the deepest.",
    "Pretty girl, but no mind.",
    "Eat in moderation and be your servant.",
    "God forbid a blind to see again.",
    "Don't let a foreign nail enter your house.",
    "If he knew, he wouldn't shit.",
    "Did a dog learn to carnage, or kill it, or the carnage burned.",
    "Wet from the rain is not afraid.",
    "A mindless tale, so the quarrel came out.",
    "A man who eats lean every day, do not spend it for meat.",
    "Can a hungry dog ​​be given cheese to guard?",
    "In one mind, in another the language of third teeth work.",
    "Beware of him who is not afraid of gentlemen and is not ashamed of people.",
    "It is better to serve the good than to command the bad.",
    "Praise me city, live in the village.",
    "Of evil kind, there is no breed.",
    "From evil, do not expect good.",
    "The good horse in the village finds its price.",
    "He doesn't build a church in the devil's village.",
    "The young want it, the old roar.",
    "He learned to shave the crazy heads.",
    "Angry Petko, his bag is empty.",
    "A lot of thunder, but a little rain.",
    "Young without memory, old without mind.",
    "The less you dance, the more you play.",
    "Every thing at a time.",
    "The cowards live longer than the fearless.",
    "The quieter you go, the farther you go.",
    "Silence overcomes everything.",
    "To better guests, more honor.",
    "Very good is not good.",
    "Better not to shout than not to do.",
    "Laziness does not eat good and does not bring new.",
    "Better a poor horse than no horse at all.",
    "The better swimmers, the more often they drown.",
    "The savages came, they drove out the tame ones.",
    "Better a poor horse than no horse at all.",
    "Strength, strength forceful, but not age-old.",
    "Feed other people's dogs, let their own bark at you.",
    "Two ears are twice to hear, two ears are twice to see.",
    "A tangled yarn on a loom is not thrown.",
    "He who breaks faith will be broken by unbelief.",
    "Better the first in the village than the last in the city.",
    "The lazy prophet becomes.",
    "Cunning, cunning outwit.",
    "It's bothering you today, you're looking for it tomorrow.",
    "You only learn with experience.",
    "From watching only glasses are put on.",
    "One learns while one is alive.",
    "Where there is a lot of manure, there is a lot of controversy.",
    "Health is the greatest property.",
    "The eagle flies high, that's why it looks far away.",
    "A bird does not spring.",
    "One knows oneself by deeds.",
    "A fast horse is enough, a quick word-no.",
    "He who believes in dreams will graze the winds.",
    "Buy a neighbor first, then a house.",
    "The dogs are barking, the caravan is moving.",
    "He turned his head, did not see where he was stepping.",
    "Fast work, double work.",
    "If you are invited by a hedgehog, if they chase you - beige.",
    "If he sat still, he would not see a miracle.",
    "Don't leave today's work for tomorrow.",
    "If he was hardworking, he would be literate.",
    "Where there is consent, there is God's attitude.",
    "Every miracle in three days.",
    "The truth swims across the sea.",
    "As a king is born, so is a hut.",
    "Two sharp stones do not grind flour.",
    "The weights of the mind teach.",
    "Lots of crafts, empty his hands.",
    "Each toad to know her bog.",
    "He who has a lot of oil, he lubricates his shoes.",
    "They talked to the donkey, it moved its ears.",
    "Beware of a young Bulgarian and an old Turk.",
    "God forbid long sticks and narrow streets.",
    "No money steel, an enemy in itself.",
    "On the fool to the waist, and the clever dry passed.",
    "God does not give horns to a prickly cow.",
    "A lot of money and a lot of care.",
    "Where there is a lot of money, there is little humanity.",
    "Rapid job shame for the master.",
    "It's good to know everything, but not to do everything.",
    "A good servant becomes a good master.",
    "The word is sharper than an arrow.",
    "On every pot of murdy.",
    "What you're full of makes you fat.",
    "The little one is made big, and the big one is made small.",
    "The language of man beautifies.",
    "As long as you have, until then they know you.",
    "A man looks at a woman's face, and a woman between the hands of a man.",
    "Hungry bear does not dance.",
    "Don't ask a fortune teller, but a heel.",
    "Feed the soul, let me listen to you.",
    "I wish my friend was nice and God would have.",
    "If you ate, you wouldn't stay.",
    "New broom, clean broom.",
    "When a hen gets fat, she doesn't lay eggs.",
    "He who sings does not think evil.",
    "If you want a big spoon, get a big hoe.",
    "The Lord helps those who seek justice, and the devil helps those who seek justice.",
    "It's easy to talk, it's hard to do.",
    "Sha slaps like a dawn.",
    "I'm the most cultured out of Burkanya (the disco), and someone stepped on my arm!",
    "Drink and hunt!",
    "God forbid, God forbid!",
    "A woman and a nail are fighting in your head!",
    "Let the poor man squeeze a fat goddess!",
    "That night a man falls, so if I'm going to be a horse!",
    "They've got so many weevils that if I take them home for three winters, we'll shine!",
    "If it's only an hour better not to start.",
    "Oooooo wait for me to zaooooaa ya moooa dooooa, moooa and not dooooa, but if dooooa do you know what moooa?",
    "Tooo scramble the cards like a drunken drey!",
    "To burn that crooked field, that barren cattle and that shoddy plowman!",
    "What the fuck is the tribe, I won't tell you who the fuck it is, so you can fuck everyone!",
    "They should put you in a suit, they should water you with wine!",
    "Whore, male ass and drunk pop are known from afar!",
    "Let's die to tour it, will we die on tour?",
    "He is one, to point at him, to measure him with tassels!",
    "Like a slap in the face, a woman slaps her door for half an hour, not that I'm strong, Una is dizzy!",
    "Oh, no romance.",
    "Were you alive, dead?",
    "Burning your wife is like beating a tethered dog - there's no thrill.",
    "Buhai ma Rangele, I'm honest, you're my second!",
    "I thought I'd show you how they take off their pants and nail them to a nail, but you see a big engine.",
    "Sha threw something with you!",
    "Hey, I'm giving it all to you, so you're sharing it as you want.",
    "Sha pa zapa nipple, ka young goat pulls cornflowers.",
    "Sha beat you when you don't want to. Do you want Sigi?",
    "Don't reach out to kick with that foot that catches up with you, then wear it with a smile.",
    "And I know her, and Dad knows, but the goat wants a stick.",
    "I've been to her personally three times for beatings, twice in the hospital and once in the intensive care unit!",
    "That girl knew where to go to bed, what to do and where to put it.",
    "One wounds and drinks, another cuts and milks!",
    "Wow goy, wow ribs count!",
    "I let him go alone and look for something to finish.",
    "Don't be afraid to fuck him, squeeze your ass and tighten the hoe!",
    "She's so ugly you don't deserve to squat to shit on him!",
    "Sha stavara too hui in the middle of the living room, fuck the whole house!",
    "Today, if you put it on his mother's pussy, ask me in the morning.",
];

export const wisdomsEn = wisdomsEnRaw.map(e => e.split(",")).reduce((acc, val) => acc.concat(val), []);